# Generated by Django 5.2.9 on 2025-12-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PilaPlanilla',
            fields=[
                ('planilla_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_interno', models.CharField(max_length=50, unique=True)),
                ('periodo', models.CharField(max_length=7)),
                ('empresa_nit', models.CharField(max_length=20)),
                ('empresa_sucursal', models.CharField(max_length=5)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'EN_PROCESO'), ('COMPLETADA', 'COMPLETADA'), ('CON_ERRORES', 'CON_ERRORES')], default='EN_PROCESO', max_length=20)),
                ('payload_inicial', models.JSONField(blank=True, null=True)),
                ('totales', models.JSONField(blank=True, null=True)),
                ('resumen', models.JSONField(blank=True, null=True)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('tiene_archivo', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pila"."pila_planilla',
            },
        ),
    ]
