# Generated by Django 5.2.9 on 2025-12-18 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pila_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilaPlanillaDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=3)),
                ('numero_doc', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('tipo_cotizante', models.CharField(max_length=2)),
                ('subtipo_cotizante', models.CharField(blank=True, max_length=2, null=True)),
                ('dias_cotizados', models.PositiveSmallIntegerField()),
                ('ibc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ibc_salud', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ibc_pension', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ibc_arl', models.DecimalField(decimal_places=2, max_digits=12)),
                ('riesgo_arl', models.CharField(max_length=1)),
                ('caja_compensacion', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('CON_ERROR', 'CON_ERROR')], default='OK', max_length=10)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pila_api.pilaplanilla')),
            ],
            options={
                'db_table': 'pila"."pila_planilla_detalle',
                'unique_together': {('planilla', 'tipo_doc', 'numero_doc')},
            },
        ),
        migrations.CreateModel(
            name='PilaNovedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_novedad', models.CharField(choices=[('VAC', 'Vacaciones'), ('INC', 'Incapacidad'), ('LIC', 'Licencia'), ('RET', 'Retiro'), ('ING', 'Ingreso'), ('VAR', 'Variable salarial')], max_length=3)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('dias', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='pila_api.pilaplanilladetalle')),
            ],
            options={
                'db_table': 'pila"."pila_novedad',
            },
        ),
    ]
