# Generated by Django 5.2.9 on 2025-12-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pila_api', '0004_alter_pilaplanilladetalle_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pilaplanilladetalle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pilaplanilladetalle',
            name='aportes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pilaplanilladetalle',
            name='aportes_empleado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pilaplanilladetalle',
            name='aportes_empleador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='pilaplanilladetalle',
            constraint=models.UniqueConstraint(fields=('planilla', 'tipo_doc', 'numero_doc'), name='uq_pila_detalle_planilla_doc'),
        ),
    ]
