# Generated by Django 5.2.9 on 2026-01-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pila_api', '0005_alter_pilaplanilladetalle_unique_together_and_more'),
    ]

    operations = [
    ]
