# Generated by Django 5.2.9 on 2026-01-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pila_api', '0006_add_dias_subsistemas'),
    ]

    operations = [
    ]
