# Generated by Django 5.2.9 on 2026-01-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pila_api', '0007_add_dias_subsistemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilaplanilladetalle',
            name='dias_arl',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pilaplanilladetalle',
            name='dias_caja',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pilaplanilladetalle',
            name='dias_pension',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pilaplanilladetalle',
            name='dias_salud',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
